import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { DarkmodeProvider } from "@/components/DarkModeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GPTQZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DarkmodeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className={cn(inter.className, "antialiased min-h-screen pt-16")}>
          <Navbar />
          {children}
        </body>
      </DarkmodeProvider>
    </html>
  );
}
